In [24]:
import numpy as np
import pandas as pd

In [13]:
np.random.seed(2)
np.random.rand(5,2)
# np.random.randn(5,2)
np.random.randint(low=0,high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

In [14]:
a = np.arange(7)

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
a >= 2

array([False, False,  True,  True,  True,  True,  True])

In [17]:
a[a>4]

array([5, 6])

## Summarize operations

In [19]:
a.sum()

21

In [20]:
a.mean()

3.0

In [21]:
a.std()

2.0

In [22]:
a.min()

0

In [25]:
pd.__version__


'1.5.3'

In [26]:
df = pd.read_csv('housing.csv')

In [27]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [37]:
df.head()


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [29]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

## Missing values

In [30]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [32]:
near_bay = df[df['ocean_proximity'] == 'NEAR BAY']

In [35]:
near_bay.median_house_value.mean()

259212.31179039303

In [38]:
df.total_bedrooms.mean()

537.8705525375618

In [41]:
df = df.fillna(df.total_bedrooms.mean())

In [42]:
df.total_bedrooms.mean()

537.8705525375617

In [43]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

## Question 7

- Select all the options located on islands.
- Select only columns housing_median_age, total_rooms, total_bedrooms.
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Compute the inverse of XTX.
- Create an array y with values [950, 1300, 800, 1000, 1300].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [104]:
islands = df[df['ocean_proximity'] == 'ISLAND']
islands = islands[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [45]:
islands.head()

housing_median_age  total_rooms  total_bedrooms
0                41.0        880.0           129.0
1                21.0       7099.0          1106.0
2                52.0       1467.0           190.0
3                52.0       1274.0           235.0
4                52.0       1627.0           280.0

In [105]:
X = islands.values

In [106]:
XTX = np.matmul(X.transpose(),X)

In [107]:
XTX_inverse = np.linalg.inv(XTX)

In [108]:
y = [950, 1300, 800, 1000, 1300]

In [111]:
w = XTX_inverse.dot(X.transpose()).dot(y)

In [112]:
w.shape

(3,)

In [113]:
w

array([23.12330961, -1.48124183,  5.69922946])